### ISSUE TITLE
Re-work event support for inline triggers

### ISSUE THREAD

**Issue by jthomas** [serverless/serverless-ibm-openwhisk#7]
Currently the event configuration in the YAML file relies on the user to define triggers separately. Users define the rule and reference an external trigger. It would be nicer to support inline trigger definition in addition to this approach. 

We should support two event types, trigger and HTTP (when API GW implementation is ready). Users should not have to define as little as possible to get up and running.

**Comment by jthomas** [comment]
We should make it easier for the developer to write inline trigger support in the function definitions and be extendable for other event types. 

This will be the new event configuration:
```
# serverless.yaml
functions:
    index:
        handler: users.main
        events:
            - trigger: "trigger_name"
            - trigger:
                name: "trigger_name"
                rule: "rule_name" 
```
The new implementation should support defining triggers in this section, rather than also having to reference triggers in the `resources` section. If the rule parameter is not used, the rule name is auto-generated with a sensible default. 

Add more trigger properties will only be supported through the `resources` section to keep the configuration terse.
